[[providers]]
name = "openrouter"
api_base = "https://openrouter.ai/api/v1"
api_key_env_var = "OPENROUTER_API_KEY"
api_style = "openai"
backend = "generic"

[[models]]
name = "openrouter/free"
provider = "openrouter"
alias = "openrouter-free"
temperature = 0.2

# Use ENV var instead: VIBE_ACTIVE_MODEL=openrouter-free
# active_model = "openrouter-free"

