FORMATTERS_DISABLE_ERRORS: false

DISABLE_LINTERS:
  - PYTHON_MYPY

# jscpd
COPYPASTE_JSCPD_ARGUMENTS: "--threshold 10"

# shfmt
BASH_SHFMT_ARGUMENTS: "--indent 2 -case-indent"

# flake8
PYTHON_FLAKE8_ARGUMENTS: "--max-line-length 120"

# kingfisher
REPOSITORY_KINGFISHER_ARGUMENTS: "--exclude .venv"

# trivy
REPOSITORY_TRIVY_ARGUMENTS: "--ignorefile ./.trivyignore.yaml"

# zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
