FORMATTERS_DISABLE_ERRORS: false

DISABLE_LINTERS:
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - REPOSITORY_DEVSKIM

PRE_COMMANDS:
  - command: >-
      python -m venv .venv &&
      .venv/bin/python -m pip install --upgrade pip &&
      .venv/bin/python -m pip install -r requirements-dev.txt
    cwd: workspace
    run_before_linters: true
    continue_if_failed: false

# flake8
PYTHON_FLAKE8_ARGUMENTS: "--max-line-length 120"

# jscpd
COPYPASTE_JSCPD_ARGUMENTS: "--threshold 10"

# kingfisher
REPOSITORY_KINGFISHER_ARGUMENTS: "--exclude .venv"

# shfmt
BASH_SHFMT_ARGUMENTS: "--indent 2 -case-indent"

# trivy
REPOSITORY_TRIVY_ARGUMENTS: "--ignorefile ./.trivyignore.yaml"

# trufflehog
REPOSITORY_TRUFFLEHOG_ARGUMENTS: "--exclude-detectors=Lob"

# zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
