name: Verify Cosign Image

description: Resolve, verify, and expose digest for the cosign image.

inputs:
  image_ref:
    description: Cosign image reference to resolve and verify.
    required: false
    default: ghcr.io/sigstore/cosign/cosign:v3.0.2

outputs:
  digest:
    description: Resolved digest for the image reference.
    value: ${{ steps.cosign-digest.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Resolve Cosign digest
      id: cosign-digest
      shell: bash
      run: |
        docker pull "${{ inputs.image_ref }}"
        digest_ref="$(docker inspect --format '{{index .RepoDigests 0}}' "${{ inputs.image_ref }}")"
        digest="${digest_ref#*@}"
        echo "digest=${digest}" >> "${GITHUB_OUTPUT}"

    - name: Verify Cosign image signature
      shell: bash
      run: |
        digest="${{ steps.cosign-digest.outputs.digest }}"
        image_name="${{ inputs.image_ref }}"
        image_name="${image_name%%@*}"
        image_name="${image_name%%:*}"
        image_ref="${image_name}@${digest}"
        docker pull "${image_ref}"
        cosign verify \
          --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com \
          --certificate-oidc-issuer https://accounts.google.com \
          "${image_ref}"
