name: Change Validation

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: change-validation-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  integration-test:
    if: github.event_name != 'push'
    uses: ./.github/workflows/integration-test.yml

  integration-test-proxy:
    if: github.event_name != 'push'
    uses: ./.github/workflows/integration-test-proxy.yml
