name: Test Suite

"on":
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/lint-and-test.yml

  integration-test:
    name: Integration
    uses: ./.github/workflows/integration-test.yml

  integration-test-proxy:
    name: Integration Proxy
    uses: ./.github/workflows/integration-test-proxy.yml
